name: movie_app
description: A Flutter movie application using TMDB API with DDD Architecture

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  
  # Network & API
  dio: ^5.3.2
  retrofit: ^4.0.3
  json_annotation: ^4.8.1
  
  # Database
  sqflite: ^2.3.0
  path: ^1.8.3
  
  # Navigation
  go_router: ^12.1.1
  
  # UI & Images
  cached_network_image: ^3.3.0
  infinite_scroll_pagination: ^4.0.0
  
  # Storage & Sharing
  shared_preferences: ^2.2.2
  share_plus: ^7.2.1
  
  # Utils
  connectivity_plus: ^5.0.1
  internet_connection_checker: ^1.0.0+1
  dartz: ^0.10.1
  get_it: ^7.6.4
  injectable: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.7
  retrofit_generator: ^8.0.4
  json_serializable: ^6.7.1
  injectable_generator: ^2.4.1

flutter:
  uses-material-design: true